---

name: try docker build & push image

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

env:
  REGISTRY: docker.io
  IMAGE_NAME: slassalle/cowsay-sla

jobs:
  login:
    runs-on: ubuntu-24.04
    steps:

      # Clonage du dépôt dans l'env github actions

      - name: Checkout repository
        uses: actions/checkout@v4


      # Récupération des méta data de l'image docker

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY  }}/${{ env.IMAGE_NAME  }}

      # Configure Docker pour se connecter à DockerHub

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Construire l'image Docker

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

