---

name: try docker build & push image

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-24.04
    steps:

      # Clonage du dépôt dans l'env github actions

      - name: Checkout repository
        uses: actions/checkout@v4

      # Configure Docker pour se connecter à Docker Hub

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Construire l'image Docker

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/cowsay-sla:latest